[package]
name = "drone-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
timer = "0.2.0"
winit = "0.28"
env_logger = "0.10"
log = "0.4"
wgpu = "0.17"
